global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nginx'
    static_configs:
      - targets: ['load_balancer:80']

  - job_name: 'web_servers'
    static_configs:
      - targets: ['web1:80', 'web2:80']
